name: CICD Pipeline 

on:
  push:
    branches: [ "" ]

jobs:

  build_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build Project
      run: mvn package

      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp.war
        path: webapp/target/webapp.war




  buils_docker_image_and_push:
    runs-on: ubuntu-latest
    needs: build_project
    steps:
    
    - name: Checkout Code
    - uses: actions/checkout@v4
    
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: webapp.war
        path: webapp/target/
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/webapp:latest



 




        
