name: CICD Pipeline 

on:
  push:
    branches: [ "main" ]

jobs:

  build_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Project
        run: mvn package

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-war
          path: webapp/target/webapp.war

  Upload_to_Nexus:
    needs: build_project
    runs-on: ubuntu-latest

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp-war
          path: /tmp

      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: http://163c6cdd.ngrok.io
          username: admin
          password: ${{ secrets.password }}
          format: maven2
          repository: maven-releases
          coordinates: groupId=com.example artifactId=webapp version=1.0.0
          assets: extension=war
          filename: /tmp/webapp.war
